---
title: "leapr_enrichment_trelliscope"
author: "Iobani Godinez"
date: "Dec 9, 2020"
output: 
  html_document:
    code_folding: hide
    lib_dir: trelli

---


```{r setup1, include = F, results= F, warning = F}
#Trelliscope display
library(trelliscopejs)
library(dplyr)
library(tidyr)
library(reshape2)
library(plotly)
library(leapr)
library(stringr)

```


```{r enrichment, include=F, results=F, warning=F}

#Pathway databases
data(msigdb)
data(ncipid)

#A sample data set is included that is from the CPTAC study of 169 ovarian tumors.
data(protdata)
data(transdata)

#We also include some groups of patients to compare:
data(shortlist)
data(longlist)

###using enrichment_wrapper function
protdata.enrichment.svl = leapR(geneset=ncipid, 
                                enrichment_method='enrichment_comparison',
                                datamatrix=protdata, primary_columns=shortlist,
                                secondary_columns=longlist)

```

```{r helper, include=F, results=F, warning=F}
#helper function takes in enrichment results and expands the "gene" column into multiple rows since each pathway contains a list of genes and not a single gene.

helper_function = function(enrichment_df, protdata){
protdata = cbind(rownames(protdata), protdata)
colnames(protdata)[1] = "gene"
    
enrichment_df = cbind(rownames(enrichment_df), enrichment_df)
colnames(enrichment_df)[1] = "pathway"

empty_gene = which(enrichment_df$ingroupnames == "")
enrichment_df = enrichment_df[-empty_gene,]
  
  tessa = mapply(function(path, gene){
                                      gene = unlist(strsplit(gene, ","))
                                      gene = str_replace_all(gene, fixed(" "), "")
  
                                      path = as.character(path)
                                      path = str_replace_all(path, fixed(" "), "")
  
                                      if(length(gene) > 1){
                                                           col1 = rep(path, length(gene))
                                                           result = cbind(col1, gene)
                                                           }else{
                                                                 result = cbind(path, gene)
                                                                }

                                      return(result)
                                      
                                      }, enrichment_df$pathway, enrichment_df$ingroupnames)


tessa = do.call(rbind, tessa)
tessa = as.data.frame(tessa)
colnames(tessa)[1] = "pathway"

enrichment_df = enrichment_df[,-which(colnames(enrichment_df) == "ingroupnames")]

new_enrichment_df = merge(enrichment_df, tessa, by= "pathway")

final_data = merge(new_enrichment_df, protdata, by = "gene", all.x = T)

return(final_data)
  
}

new_data = helper_function(protdata.enrichment.svl, protdata)

```

```{r plot_helper, include=F, results=F, warning=F}
library(magrittr)
#here we create another helper function but to plot the data within the "make_trell" function 
plot_helper = function(single_df){
  #since we used "helper_function" to organize the data we need to extract the columns with abundance values to form a heatmap plot
  single_subset = single_df[ , c(1, 13:186)]
  
  #rownames(single_subset) = single_df$gene
  single_subset = single_subset %>% data.frame %>% set_rownames(.$gene) %>% select(-gene)
  
  single_subset = as.matrix(single_subset)
  
   result = plot_ly(x = colnames(single_subset), y = rownames(single_subset), z = single_subset, zmin = round(min(single_subset, na.rm = T)), zmax = round(max(single_subset, na.rm = T)/4), type = "heatmap", colorscale = "YlOrRd") %>% layout(yaxis = list(showticklabels = F, title = "abundance"), xaxis = list(title = "sample name", showticklabels = T))
  
  return(result)
  
}

```

```{r trelliscope, include = T, results= T, warning = F}

#here we work on a function to take in the enrichment results dataframe (new_data from the above chunk) and return a trelliscope display where each panel is a pathway that displays enrichment statistics

make_trell = function(new_data){
  
  #replace na and nan values with zeros
   new_data[is.na(new_data)] = 0
  
  #we need to subset data for each pathway
   tess2 = new_data %>%
   group_by(pathway) %>%
   nest() %>%
   ungroup() %>%
   mutate(cogs = map_cog(data, ~tibble(
                                   
                                           ingroup_mean = cog(.$ingroup_mean[1], desc = "ingroup mean"),
                                           outgroup_mean = cog(.$outgroup_mean[1], desc = "outgroup mean"),
                                          
                                           )
                        ),
                          panel = map_plot(data, ~plot_helper(.)
                          )
         )
   
final2 = trelliscope(tess2, name = "first trelliscopejs", self_contained = T, path = "trelli")
return(final2)
   
  
}


display = make_trell(new_data)
display
```







